-- 코드를 입력하세요
SELECT PRODUCT_ID, 	PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL
FROM FOOD_PRODUCT NATURAL JOIN FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL DESC, PRODUCT_ID
